### ISSUE TITLE
[Bug] blocking (blpop) timeout lead to confusing RedisErrors

### ISSUE THREAD

**Issue by darklajid** [aembke/fred.rs#104]
Redis version - 7.0.9
Platform - windows
Using Docker and/or Kubernetes - yes
Deployment type - centralized

**Describe the bug**
The easy/trivial `client.blpop::<(String, String), _>("key", timeout).await` can, in my opinion, return three things:

* A value from the given list
* A timeout
* A generic Redis error

Right now, there doesn't seem to be a good way to separate the last two. Fred returns a `RedisError` with "Redis Error - kind: Parse, details: Could not convert to tuple." which .. is fair, I guess. There wasn't a tuple. There was a timeout. Which doesn't quite feel like an error case to me and IF it should be a `RedisError` then the message is still confusing/wrong.

**To Reproduce**
1. blpop a string, string tuple from an empty list
2. wait for timeout

**Comment by aembke** [comment]
Makes sense. The underlying issue is that Redis doesn't actually return any kind of error on a timeout, rather it just returns `nil`, and trying to convert `nil` to `(String, String)` goes through the more generic type conversion logic. 

I'll add some special case logic to blpop/brpop so that it converts `nil` to a `RedisErrorKind::Timeout` error.
