### ISSUE TITLE
Disallowing nested items interferes with `serde_json::Value`

### ISSUE THREAD

**Issue by oren0e** [aembke/fred.rs#113]
It is exteremly unclear how can you write an impl of `FromRedis` for a custom struct in the case that you want to set a key:value with the value being a JSON. So instead when using the `.set()` it is possible to pass `serde_json::Value` - but it seems that it does not work because it cannot deal with nesting because of https://github.com/aembke/fred.rs/blob/main/src/utils.rs#L530. This makes it impossible to set a value of a custom struct as a json.

**Comment by aembke** [comment]
I think there may be some miscommunication here, likely because of how loosely the `serde_json::Value` -> `fred::RedisValue` mapping logic is implemented. My intention with that conversion logic was to support one specific use case: using `Value::Object` interchangeably with `RedisValue::Map`, and more specifically with `hgetall`. 

It's true that you can also use that conversion logic to pass `serde_json::Value` into almost any function that supports `TryInto<RedisValue>`, but in most cases I'd argue that wouldn't work or make sense. Usually what you want is to stringify/serialize your `Value` and then deserialize it when you read it back later (as shown in [the serde example](https://github.com/aembke/fred.rs/blob/main/examples/serde.rs#L39-L53)). 

More specifically, see these docs: https://redis.io/docs/reference/protocol-spec/#resp-protocol-description

> Clients send commands to a Redis server as a RESP Array of Bulk Strings.

The `disallow_nested_values` function is there to enforce that requirement on the client side before frames are sent out. Even if I were to remove that check you'd just get an `InvalidArgument` error from the server. 

I may just remove the `serde_json::Value` -> `fred::RedisValue` conversion logic in the future to avoid this confusion. I think the majority of the utility with that feature comes from mapping in the other direction (`RedisValue` -> `Value`) anyways. We'll see though, I think this needs some more thought, but I can see where the confusion comes from.

**Comment by aembke** [comment]
I removed this in 7.x since it clashed with some other automatic parsing logic and introduced some ambiguity across the hset/hmset/hgetall interfaces.
