### ISSUE TITLE
Change log print format [Bug]

### ISSUE THREAD

**Issue by daji777** [aembke/fred.rs#124]
Redis version - 6.1.0
Platform - linux|mac|windows
Using Docker and/or Kubernetes - yes|no
Deployment type - cluster|sentinel|centralized

**hi，developers，I found the error log from reconnecting failed is debug format , that means I open info mode, I cannot realize this error when the redis is disconnected.**

**To Reproduce**
 if let Err(e) = router.connect().await {
    _debug!(inner, "Failed reconnecting with error: {:?}", e);
    client_utils::set_client_state(&inner.state, ClientState::Disconnected);
    inner.notifications.broadcast_error(e.clone());
    Err(e)
  } 

**Logs**
(Set `RUST_LOG=fred=trace` and run with `--features debug-ids`)

**Additional context**
I hope this _debug mode can be set to _error，thanks a lot

**Comment by aembke** [comment]
Hi @daji777 ,

That line is intentionally a `debug` level log because it runs whenever the client connection finishes - either via a fatal error, QUIT, SHUTDOWN, etc. If I were to change it to an `error!` log level then it would mislead callers into thinking normal calls to QUIT were causing errors. Additionally, that log line only runs when the last reconnection attempt fails, which does not sound like what you want.

If you want to print a log line whenever the client disconnects then I'd recommend [something like this](https://github.com/aembke/fred.rs/blob/4afdddcc4c496526c63ac9b84ff9fb9c355526ab/examples/basic.rs#L44-L48):

```rust
let mut error_rx = client.on_error();

tokio::spawn(async move {
  while let Ok(error) = error_rx.recv().await {
    println!("Client disconnected with error: {:?}", error);
  }
});
```

**Comment by aembke** [comment]
If you do want to use a built-in log line for detecting closed connections I'd recommend [this one](https://github.com/aembke/fred.rs/blob/4668d41136938fc5dd42b4d2a8a71a789e7cb42e/src/router/responses.rs#L313).

**Comment by daji777** [comment]
@aembke  I did a experiment before and I had a redis-cluster with 3 shardings. and I stopped one master of this cluster , During the shutting down , I didn't see any errors print out . 

shard 1	
10.100.42.166:7000(master)
10.100.42.166:7004(slave)
shard 2	
10.100.42.166:7002(master and stop)
sahrd 3	
10.100.42.166:7001(master)
10.100.42.166:7005(slave)
