### ISSUE TITLE
[Bug]Questions about library selection

### ISSUE THREAD

**Issue by Zheby** [aembke/fred.rs#223]
Redis version - 7.2
Platform - linux
Using Docker and/or Kubernetes -no

**Describe the bug**
![image](https://github.com/aembke/fred.rs/assets/113359077/fd6dce58-a6b5-45a8-a301-c6b0368f9214)

**To Reproduce**
Create two inserts, the first into the first library and the second into the other library

Not Log

**Comment by aembke** [comment]
Hi @Zheby , can you provide more of the code or show how you're calling `add_basic`?

Either way I would recommend using [the database field](https://docs.rs/fred/latest/fred/types/struct.RedisConfig.html#structfield.database) when initializing a client rather than changing databases after connecting.
