### ISSUE TITLE
Question: Is fred.rs a thread-safe?

### ISSUE THREAD

**Issue by hideki** [aembke/fred.rs#23]
Thank you very much for developing and maintaining awesome Redis library. This is a question, not the bug report. I am wondering if fred.rs is a thread-safe?

**Comment by aembke** [comment]
Hi @hideki,

Yes everything in Fred should be thread safe in that all of the public interface and types are at least `Send`, and the various client structs are all `Send + Sync`.

In the future I might add a new client struct that is not `Send` or `Sync` in order to take advantage of some performance improvements that depend on [LocalSet](https://docs.rs/tokio/0.2.4/tokio/task/struct.LocalSet.html) and friends, but I don't have any immediate plans to release that. If or when I do release that it'll be behind a new feature flag or a new client type that makes this clear to callers.

**Comment by hideki** [comment]
@aembke I am glad to hear that fred.rs is thread safe, and thank you for detailed explanation!
