### ISSUE TITLE
[Bug] Cannot return integer type from `exists`

### ISSUE THREAD

**Issue by maxcountryman** [aembke/fred.rs#231]
Redis version - Redis 7.2.1 
Platform - mac
Using Docker and/or Kubernetes - no
Deployment type - Running in standalone mode

**Describe the bug**

Attempting to use `exists` within a transaction does not seem to work. No type can be returned besides unit. 

Logs via `dbg!`:

```
tx.exists::<i64, _>(record.id.to_string()).await = Err(
    Redis Error - kind: Parse, details: Cannot convert to number.,
)
```

**To Reproduce**
1. Call `exists` on a transaction with a return type besides unit

**Comment by aembke** [comment]
So the root cause is that the server actually returns `"QUEUED"` to all commands within a MULTI block, and the client mimics that response when buffering commands before `exec`, and there's no automatic type conversion from the string "QUEUED" to an `i64`. If you know that you're in a multi block I'd recommend using `RedisValue` as the return type, or manually check for `QUEUED` via https://docs.rs/fred/latest/fred/types/enum.RedisValue.html#method.is_queued.

**Comment by maxcountryman** [comment]
Thanks, using `RedisValue` seems to fix the deserialization problem.

My goal here is to check if a key already exists and if it does generate a new key before inserting, all within the same transaction, i.e. atomically. Maybe there's a better approach?

**Comment by aembke** [comment]
Maybe something like this?

```rust
  loop {
    let key = generate_key();
    let result: RedisValue = client.set(key, "value", None, Some(SetOptions::NX), false).await?;

    if result.is_null() {
      // key already existed
      continue;
    }else{
      break;
    }
  }
```

**Comment by maxcountryman** [comment]
Perfect--that seems like a much better approach. Thank you!
