### ISSUE TITLE
Waiting for exec to return from server

### ISSUE THREAD

**Issue by mkurtak** [aembke/fred.rs#25]
Hi,
I don't know if it's an intended behavior, but I ran into following situation:

Suppose you have 10ms latency to Redis. Every 5ms you application needs to run
```
MULTI
HSET key value
PUBLISH message
EXEC
```
I am using the following code to execute this sequence in fred:
```rust
let trx = redis.multi(true).await?;
trx.hset(key, hashmap! { field => value.into()}).await?;
trx.publish(channel, message).await?;
trx.exec().await?;
```
I'd like to have a writer that executes this code, but waits for the response in a new tokio task every 5ms. This way there will be 2 running requests waiting for responses.
I don't know how to achieve this with fred.

There are 2 issues:
* Fred allows to call another MULTI once the response from EXEC has arrived. I think new MULTI can be allowed once the EXEC has been sent
* It's not possible to split the sending the commands and receiving the response. I don't know when it is safe to call second MULTI

Thanks for help

**Comment by aembke** [comment]
Hi @mkurtak,

I'm not sure I fully understand the use case or how the redis latency comes into play, but maybe if you have a small snippet that illustrates what you're trying to do that might help.

That being said, I can maybe address your two bullet points:

> Fred allows to call another MULTI once the response from EXEC has arrived. I think new MULTI can be allowed once the EXEC has been sent 

This is intended since the server wont allow you to send a second MULTI before receiving an EXEC/DISCARD for the first anyways. With fred this is implemented where we disallow the next MULTI until the EXEC/DISCARD response is received (as opposed to being sent). We wait for a response before allowing another transaction in order to detect cases where the connection closes while the EXEC/DISCARD is in-flight. Even when the caller specifies the pipeline flag the client will still always wait for the EXEC/DISCARD response before allowing another MULTI. 

> It's not possible to split the sending the commands and receiving the response. I don't know when it is safe to call second MULTI

I may not fully understand your use case, so take this with a grain of salt, but this strikes me as an issue callers would face any time they have concurrent tasks sharing a connection where at least one task is using the transaction interface. At first glance this seems like it would require some form of synchronization between the tasks, but I might be misunderstanding something.

That being said, it _should_ be possible to do what you want with fred, but in its current state it might be pretty difficult. I can imagine supporting this in cases where the client was not pipelined and the caller made sure EXEC was called before the next MULTI, even if the MULTI command was sent prior to the EXEC response arriving. I intended to support this use case when I made MULTI, EXEC, and DISCARD act like blocking commands to allow for this exact thing, but I don't think I ever tested this with concurrent tasks so I'm not sure how this would look or whether it actually works reliably without some form of manual synchronization. 

I'll need to think on if there's a way to do this in a clean way in fred though. Or if I'm misunderstanding your use case please let me know.

**Comment by aembke** [comment]
Just to expand on the first part a bit more - fred waits for the EXEC response to come back before allowing another MULTI to avoid the following situation:

1. The caller starts a transaction.
2. The caller sends EXEC or DISCARD.
3. The caller sends MULTI to start a new transaction.
3. While the EXEC/DISCARD is in-flight to the server the connection dies.
4. The replay logic replays EXEC/DISCARD, then MULTI. To the transaction task everything looks fine so far. 
5. A bunch of `on_reconnect` logic runs that doesn't account for it being run in a transaction. The caller sees all sorts of errors due to not expecting a "QUEUED" response from the server in this context.

For this reason fred makes sure that transactions start and finish fully on a healthy connection. Or if that cant happen then we abort the transaction.

**Comment by mkurtak** [comment]
Hi @aembke,

I understand your point. We are migrating from javascript ioredis, which ends a transaction when exec is sent. We are using redis that has higher latency than the writer. 

I am not sure how would LUA solve the issue. Do you suggest to install LUA script on server and then send commands calling functions from client? Does fred allow to have multiple LUA scripts in-flight?

I'll prepare an example during the weekend.

**Comment by mkurtak** [comment]
Sorry @aembke I didn't have time to prepare the example, but I understand your point. Should I close the issue?

**Comment by aembke** [comment]
@mkurtak I think I understand where you're coming from in that it's currently difficult with the current interface to synchronize transactions across different concurrent tokio tasks. Callers could do this with an async mutex, but that's pretty tedious. 

I'm in the middle of the next major version at the moment so I have some flexibility to change the interface to make this easier. The client currently supports a `in_transaction()` function that can be used to check if another task is using the connection for a transaction, but that's not really that useful since then callers are forced to sleep or spin before checking that value again. 

If I added an interface that allowed callers to wait for a transaction to finish would that help?

**Comment by mkurtak** [comment]
@aembke thanks for your help. Actually, the bigger problem is that there is no possibility to have multiple running transactions, so we will probably migrate to Lua. 

I think having this feature would be nice, but since we will not use it, I don't want to push you in this direction.

**Comment by aembke** [comment]
Sounds good. If `ioredis` allows for multiple concurrent transactions they must either be queueing commands up in memory before sending anything (with their own synchronization in the client), or they must be creating new connections on the fly. A transaction sets global state on the connection so callers can't use multiple transactions on the same connection at the same time. 

Fred takes a different approach and won't create multiple connections, so doing this with fred would likely require some more invasive design changes to your app. Or, like you said, if you switch to lua then there's no connection state change, so everything tends to become simpler. 

I'll close this out in the meantime, but let me know if you have issues with the lua interface.

**Comment by Alkeryn** [comment]
@aembke sorry for the bump but wouldn't it be possible to have a form of queue so that you can allow creating multiple transactions on different threads / tokio tasks, but it will make them wait for them to complete upon exec ?.
this way you don't have to fail tasks or implement some crazy waiting within them or make a form of lilo queue yourself.

the way it works right now the performance penality can be high for things like actix web.

**Comment by aembke** [comment]
Yeah absolutely that's a good idea. This is good timing too because that'd be a breaking change to the transactions interface, but I'm planning on releasing a new major version soon.

The tradeoff with this approach is that you wont necessarily get immediate feedback on intermediate commands failing prior to the exec/discard. However, with this approach it would be quite a bit easier to do retry on entire transactions, and would also likely make it easier to reason about concurrent transactions like you mentioned.

**Comment by aembke** [comment]
The way I'll likely do this is to add a new interface (perhaps a `multi_buffer` function) that returns a modified version of a `TransactionClient` which will buffer commands in memory until EXEC or DISCARD is called. Following the EXEC the client would send all the commands, perhaps in one pipelined series of commands if configured by the caller. 

Unfortunately this would require some pretty invasive changes to the client, so I'll need to think more about how to do this. Depending on how invasive this is I may have to push it out to 5.1.0 instead of the upcoming 5.0.0 release.

**Comment by Alkeryn** [comment]
thanks man, take the time you need, i mean you are providing us with a great lib for free, i'm not gonna complain !
though one thing i'd really want too is manual pipelining, that'd be great ^^

**Comment by Alkeryn** [comment]
@aembke here is an example case scenario where i'd have wanted to use manual pipelining.
users can like another users's profile, but to waste less trafic, i send them as an array of a hundred likes instead of doing a get request each time.

the array contains a list of userid to be liked.

so i end up doing a bunch of zadd in a row.
can't use multi key commands as it'll be clustered and putting them in a hash tag didn't seem like a good solution to me.

rn the best option i found was to make a vector of futures for all of the zadd's and await them all at once.

if i could just pipeline all the commands in one go that'd be neat.

i'd imagine something like have a pipe object where you can just add commands to just like if it was a session, and then send them all at once with a single await.

what do you think ? :)

**Comment by Alkeryn** [comment]
thanks for all these detailed explications ! :)
you put a lot of time into writing it, even more so with the graphs and all ! :)

however i was just curious about something, for some reason running await in a for loop is slightly faster than running them all 
without await then joining, i might try the join_all as well, i was just toying around.
but here is a sample of code :
```rust
// this is faster
  let mut k : String = String::new();
  
  for i in 0..100 {
      k = db.get::<String, _>("key").await?;
  }                                               
```
```rust
// this is slower
let mut v : Vec<_> = Vec::new();
let mut k : String = String::new();

for i in 0..100 {
    v.push(db.get::<String, _>("key"));
}

for i in v {
    k = i.await?;
}
``` 
do you have any idea why ? :)

**Comment by aembke** [comment]
Hmm, that's interesting. Those should have the exact same behavior on the wire, but there might be some strangeness going on with the scheduler there. Under the hood each request uses a oneshot channel to respond to the caller, and I've seen some strange performance behavior there. Often it's not bad, and in many cases it's actually fast when I expect it to be slow and vice versa, but I was never able to figure out why. 

For example, [here's a similar thing I encountered in the pool implementation](https://github.com/aembke/fred.rs/pull/15/files?diff=unified&w=0#diff-000d27d9156c3c418c25422efb6b29b87d146f55946336e3ea4dc4fcf5fce387R348-R350). I thought the old behavior should work (essentially doing what you're doing with await in a loop). but in fact it had a race condition where it wouldn't work. But once I switched to using `join` it not only worked every time, but also was much faster. In the end one I've come to realize is that tokio is a strange beast and if you want futures to run concurrently you should always use `select`, `join`, etc, instead of loops with `await`.

**Comment by aembke** [comment]
If you have a jaeger (or whatever tracing vendor you prefer) setup going locally you could try turning on partial tracing to see the difference here too. That might help answer some of the questions. The [pipeline test](https://github.com/aembke/fred.rs/tree/main/bin/pipeline_test) code shows how to do this if you want to take some time to set that up.

**Comment by aembke** [comment]
I'm going to put a note about this in the TODO list and take a look at it for 5.1.0. in the meantime i'm going to close this for now, but feel free to reopen.
