### ISSUE TITLE
[Feature] TransactionInterface for Pipeline

### ISSUE THREAD

**Issue by ItsEthra** [aembke/fred.rs#274]
I noticed that `Pipeline<T>` does not implement TransactionsInterface which means I cannot use `MULTI` on it. Is there any specific reason why it's not implemented? AFAIK Commands in a pipeline are not executed together as a transaction.
And also commands in a transaction are not executed in a pipeline(see below).

![image](https://github.com/user-attachments/assets/56346f96-5d98-4ebe-99a5-5ab6fe6d94f6)

But I want to have commands executed together in a transaction AND in a pipeline together so I can cut on round trips and have them executed in order.

**Describe the solution you'd like**
I would like to see `TransactionsInterface` implemented for `Pipeline<T>`.

**Comment by aembke** [comment]
Yeah, I intentionally disallowed that in order to properly handle cluster redirections in the middle of transactions. The docs state that clients should DISCARD a transaction in response to a MOVED/ASK error, then replay the entire transaction on the new node, and the only way I could think to do that safely in a transaction was to wait for a QUEUED or MOVED/ASK response from each command.

**Comment by aembke** [comment]
After looking into this a bit more it seems Redis has supported this since 2.6.5. In [9.2.0](https://github.com/aembke/fred.rs/pull/288) there will be a new `pipeline` function on the `Transaction` struct that can do this.

**Comment by aembke** [comment]
Added in https://github.com/aembke/fred.rs/releases/tag/v9.2.0, but let me know if you have any issues with it.

**Comment by aembke** [comment]
All transactions are pipined automatically now in 10.x.
