### ISSUE TITLE
[Feature] Scale reads across replicas.

### ISSUE THREAD

**Issue by CR7273868** [aembke/fred.rs#286]
**Describe the solution you'd like**
Scaling reads across replicas. The pool manager is awesome. I would like to get an option just like IOREDIS has to scale reads across replicas. This could fit nicely into the replicas feature. Where CLUSTER support & so on is all taken into account. And this also goes for pubsub. When commands like SSubscribe, subscribe & etc... are issued it will resort to a replica rather than a master node.

**Additional context**

**Comment by aembke** [comment]
Hi @CR7273868, 

Have you tried the `replicas()` decorator function? I think that should do what you're describing. In some of my code I use it like so:

```rust
struct State {
  // these two will automatically stay in sync as nodes change, etc
  pool: RedisPool,
  replicas: Replicas
}

async fn example() {
  let pool = Builder::default_centralized().build_pool(5).unwrap();
  let replicas = pool.replicas();
  let state = State { pool, replicas };
  
  // talk to primary nodes with state.pool
  let foo: String = state.pool.set(...).await.unwrap();
  // talk to replica nodes with state.replicas
  let foo: String = state.replicas.get(...).await.unwrap();
}
```

Or maybe I'm misunderstanding and you were looking to have the client automatically detect reads vs writes and send reads to replicas? For what it's worth I considered that initially but decided against it because Redis' replication is asynchronous and automatically sending reads to replicas could create unexpected consistency issues for callers. Unfortunately it's actually pretty involved to enforce strong consistency across replicas: https://github.com/aembke/fred.rs/blob/main/examples/replicas.rs#L46-L62

I could consider maybe making this optional behind a new flag on the `ReplicaConfig` though.

**Comment by CR7273868** [comment]
Hi @aembke,

That will work perfectly and yes I looked at it. I got a tad bit confused with Pubsub. No big deal. This seems to be the only library that is effective & well coded with Redis Clustered PUBSUB across multiple servers.

Good job btw. Nice to see there is something out here that works and well polished.
