### ISSUE TITLE
[Bug] Vec<u8> is recognised as Array rather than Bytes

### ISSUE THREAD

**Issue by dracarys18** [aembke/fred.rs#296]
Fred version - 9.2.1
Redis version - 7.0.1
Platform - mac
Deployment type - cluster|sentinel|centralized

**Describe the bug**
For the following example below, Fred throws and error ` value: Redis Error - kind: InvalidArgument, details: Invalid argument type: Array` while it's a valid type.
```rust
    let v = client.hsetnx::<E, &str, &str, V>("bruh1", "what1", serde_json::to_vec(&data).unwrap()).await;
```
**To Reproduce**

1. Call `hsetnx` function with `Vec<u8>` as value type.

**Logs**
(If possible set `RUST_LOG=fred=trace` and run with `--features debug-ids`)

Redis Error - kind: InvalidArgument, details: Invalid argument type: Array

**Comment by dracarys18** [comment]
I can take this up we need a different `TryInto` implementation for `Vec<u8>` and `Vec<T>` where T is not `u8`

**Comment by aembke** [comment]
Hi @dracarys18,

Unfortunately I'm not sure how to do this on stable rust at the moment without [specialization](https://github.com/rust-lang/rust/issues/31844), but feel free to submit a PR if you can make it work. 

After looking at this a bit more - If I'm reading this correctly it looks like `TryFrom<T>` creates a `From<T>` fallback automatically, and since `From<u8>` already exists we can't implement both `TryFrom<Vec<u8>> for RedisValue` and `TryFrom<Vec<T>> for RedisValue`. 

I think there's a few ways to work around this, but they have some downsides:
* Convert to `Vec<RedisValue::Integer>` and back to bytes (safe but expensive)
* Wait for specialization (unstable at the moment)
* Remove the `From<u8> for RedisValue` impl (breaking)
* Use `mem::transmute` (unsafe, and probably not useful since it would have to be used with TypeId::of(), which requires T: 'static, which is breaking)
* Use a different trait other than `TryFrom` to do these type conversions (breaking)

For the next major version I'll probably remove the `From<u8> for RedisValue` since `Vec<u8>` is likely much more common, but for now I want to avoid any breaking changes.

**Comment by dracarys18** [comment]
@aembke I like the idea of last point can we make a feature flag for this so it wont break for others and slowly release it in the next release

**Comment by aembke** [comment]
Sounds good. In [9.4.0](https://github.com/aembke/fred.rs/pull/308) there a new FF `specialize-into-bytes` that will disable `From<u8> for RedisValue` and enable `TryFrom<Vec<u8>> for RedisValue` such that it uses `RedisValue::Bytes`.

**Comment by dracarys18** [comment]
Oh that's awesome! Thanks @aembke

**Comment by aembke** [comment]
Added in [9.4.0](https://github.com/aembke/fred.rs/releases/tag/v9.4.0)
