### ISSUE TITLE
[Feature] fix Scan stream API

### ISSUE THREAD

**Issue by sitano** [aembke/fred.rs#305]
**Describe the solution you'd like**

`client.scan("*", ...) -> impl Stream<item = Result<RedisKey, RedisError>>`

**Additional context**

this is super non-trivial and basically breaks normal stream API:

```
client.scan("*", ...) -> impl Stream<item = Result<ScanResult, RedisError>>
```

that is also expects `scan.next()` inside without which it is silently does not work correctly - this is super non-unintuitive.

**Comment by aembke** [comment]
Can you be more specific on how this breaks the stream API? 

Regarding `page.next()` - do you have a pattern you'd like to see that supports asynchronous pagination while supporting the ability for callers to defer the next pagination request?

**Comment by sitano** [comment]
> Can you be more specific on how this breaks the stream API?

What I am expecting from the API is to get a `stream of keys` (`impl Stream<item = Result<RedisKey, RedisError>>`) so I can `fold` it, `collect` it or `map`. What `stream of ScanResults` directly implies is to have a map function with a loop inside that should (1) iterate of the scan results and then (b) also call next(). There are at least 2 flaws in the design here:

- missing of the scan result next() call silently breaks the stream correctness without any warnings
- it prevents writing stream transformation in functional style with Flap/Maps as the first thing to do is to map the stream returned from the Scan() into the normal one with an imperative approach.

> Regarding page.next() - do you have a pattern you'd like to see that supports asynchronous pagination while supporting the ability for callers to defer the next pagination request?

I am not fully understanding if it is an issue to hide the ScanResult into the object that implements Stream with next() inside and expose Stream of Item=Key such that next() only called when the current scan result batch is fully consumed.

**Comment by aembke** [comment]
There's a few new scanning interfaces in the recent versions, but especially the latest v10.0.0 release, and the one you want is most likely `scan_buffered` or `scan_cluster_buffered`.  For what it's worth, you probably want to use Tokio's `StreamExt` trait since it has a more flexible `collect` implementation, at least based on my testing. 

Some examples: 
* https://github.com/aembke/fred.rs/blob/main/examples/scan.rs#L40-L49 
* https://github.com/aembke/fred.rs/blob/main/tests/integration/scanning/mod.rs#L177-L194

Let me know if those interfaces don't work for you though.
