### ISSUE TITLE
Questions: Read selection strategy and failing replica node handling

### ISSUE THREAD

**Issue by tsukit** [aembke/fred.rs#32]
This is actually questions, not issues. I can't seem to find the info around this.

1) For reading, what's the reading strategy among replica nodes? Round-robin? Or something different? Can it be configured?

2) How does the `RedisClient` handle a failing replica node? 

Thank you.
Ed

**Comment by aembke** [comment]
So currently Fred doesn't use replica nodes at all. I have a big TODO in the code to handle this in the future, but for now the library ignores them.

There are some big gotchas with Redis and replicas due to the fact that replication is asynchronous, and for my purposes at least at work this is a problem. Redis recently added the WAIT command to deal with some of this, but frankly I'm not a fan of that strategy. There are a number of distributed systems folks that have written better blog posts, etc, on this, so I won't repeat it here.

I do plan on adding replica node support for reads in the future, but it's not likely something I'm going to get to for a bit here. However, if you do need that you can always point a centralized client at a replica and ensure that you use read-only commands, however that's not a great solution.

**Comment by tsukit** [comment]
Thanks so much @aembke  for the in-depth info! This is pretty help. Our internal clusters are currently sentinel-managed (soon to be running in cluster mode) and we use replicas to distribute reads as the most of the stacks we have are read heavy. When do you think will the ability to read from replicas (the the ability to handle its failure) be available? All ballpark estimate is highly appreciated.

**Comment by aembke** [comment]
So if you're using the sentinel interface the failover scenarios are handled today. The same for clusters assuming you're using some sort of management layer that can run the CLUSTER commands to promote a replica to a primary node such that it'll show up as a primary in subsequent CLUSTER NODES responses. 

As far as sending reads to replicas without any failure taking place - that's probably a couple months out. My biggest focus after the upcoming 5.0.0 release will be on deep refactoring to make transactions easier to reason about, and then I'll likely start performance tuning work including this kind of automatically-send-reads-to-replicas work.

**Comment by tsukit** [comment]
Thanks @aembke. Look forward to having that support.

**Comment by aembke** [comment]
Sounds good, when that's ready or nearing completion I'll tag you so you have a heads up. In the meantime I'm going to close this out and track this in a set of wiki pages that I'm working on for this repo.
