### ISSUE TITLE
How to set a map value

### ISSUE THREAD

**Issue by fy2462** [aembke/fred.rs#34]
Hi all:

I want to set a map data with `RedisMap`

```rust

let redis_key = "KEYS".into();
let mut redis_map_value = RedisMap::new();
redis_map_value.insert(
       "foo_key".to_string(),
      RedisValue::Integer(123),
 );
let value = RedisValue::Map(redis_map_value);

let _ = redis_client
                .set::<RedisValue, String, RedisValue>(
                    redis_key,
                    value,
                    Some(Expiration::EX(10)),
                    None,
                    false,
                )
                .await;


```

No error was found, but I can not get the key and value in Redis server also, what's happened, and how to do that?

**Comment by aembke** [comment]
Ah I should do a better job documenting this, but `RedisMap` was built to be a NewType in order to support generic inputs on certain functions. It is designed to be used as an intermediate type so callers can use `HashMap` or `BTreeMap`, but it's rare for a caller to need to manually construct a `RedisMap` by hand.

In your case you can probably collapse that code into this:

```rust
let _: () = redis_client.set("foo_key", 123, Some(Expiration::EX(10), None, false).await?;
```

But if you did need to use a map, such as for HSET, you could do it like so:

```rust
let mut values: HashMap<String, i64> = HashMap::new(); // or BTreeMap, etc
values.insert("bar".into(), 123);

let _: () = redis_client.hset("foo", values).await?;
```

A quick note on the NewType values such as `RedisMap` - they are not as easy to use in the current 4.3.2 version on crates.io as I'd like. I'm a few days away from releasing 5.0.0 which makes some big ergonomics improvements to these types, and these interfaces should be easier to use then.

**Comment by fy2462** [comment]
The `hset` command seems what I want, Thanks.

**Comment by fy2462** [comment]
I found I can not set `Expiration` with `hset`, How to do that as `set` ?
